"""Regenerate the frontend content file(s) (src/content/cvData.js and
frontend/src/content/cvData.js) from the merged profile snapshot so the
statically-deployed Vite site shows the synced LinkedIn data after a
rebuild/redeploy.
"""
import json
import os

from app.services.store import BASE_DIR

# Both the root legacy tree and the npm-workspace frontend are covered,
# whichever one Vercel/npm picks up stays current.
TARGETS = [
    os.path.join(BASE_DIR, "src", "content", "cvData.js"),
    os.path.join(BASE_DIR, "frontend", "src", "content", "cvData.js"),
]

_HEADER = """// AUTO-GENERATED by the LinkedIn sync backend — do not edit by hand.
// Run:  backend/venv/Scripts/python.exe backend/scripts/sync.py --import <file.json>
// or:   POST /api/linkedin/sync   |   POST /api/linkedin/import
// Manual edits are preserved in backend/data/profile.json and re-applied.

"""


def _fmt(value):
    """JSON dump suitable for embedding in JS."""
    return json.dumps(value, indent=2, ensure_ascii=False)


def generate(profile):
    """Write every cvData.js target from the merged profile dict."""
    body = {k: v for k, v in profile.items() if k != "meta"}
    js = _HEADER + "export const cvData = " + _fmt(body) + ";\n"
    written = []
    for target in TARGETS:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        tmp = target + ".tmp"
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write(js)
        os.replace(tmp, target)
        written.append(target)
    return written

