"""Regenerate the deployed frontend content file from the merged profile
snapshot so the Vite site reflects the latest LinkedIn sync.
"""
import json
import os

from app.services.store import BASE_DIR

TARGETS = [
    os.path.join(BASE_DIR, "frontend", "src", "content", "cvData.js"),
]

_HEADER = """// AUTO-GENERATED by the LinkedIn sync backend — do not edit by hand.
// Run:  backend/venv/Scripts/python.exe backend/scripts/sync.py --import <file.json>
// or:   POST /api/linkedin/sync   |   POST /api/linkedin/import
// Manual edits are preserved in backend/data/profile.json and re-applied.

"""


def _fmt(value):
    """JSON dump suitable for embedding in JS."""
    return json.dumps(value, indent=2, ensure_ascii=False)


def _atomic_write(target, content, attempts=10, delay=0.25):
    """Write via temp file + replace, retrying briefly on PermissionError.

    On Windows, dev-server file watchers / AV scanners can hold the target
    file for a moment right after it changes, making an immediate second
    os.replace() fail with Access Denied.
    """
    import time

    tmp = target + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(content)
    for attempt in range(attempts):
        try:
            os.replace(tmp, target)
            return
        except PermissionError:
            if attempt == attempts - 1:
                raise
            time.sleep(delay)


def generate(profile):
    """Write every cvData.js target from the merged profile dict."""
    body = {k: v for k, v in profile.items() if k != "meta"}
    js = _HEADER + "export const cvData = " + _fmt(body) + ";\n"
    written = []
    for target in TARGETS:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        _atomic_write(target, js)
        written.append(target)
    return written

