// AUTO-GENERATED by the LinkedIn sync backend — do not edit by hand.
// Run:  backend/venv/Scripts/python.exe backend/scripts/sync.py --import <file.json>
// or:   POST /api/linkedin/sync   |   POST /api/linkedin/import
// Manual edits are preserved in backend/data/profile.json and re-applied.

export const cvData = {
  "name": "Muhammad Faraz Kazmi",
  "title": "AI Engineer & Python Developer",
  "tagline": "Building Intelligent Solutions for the Real World",
  "bio": "Aspiring AI Engineer and Python Developer with a strong passion for building practical, real-world solutions through technology. Actively developing skills in Python, Machine Learning, and Deep Learning to design impactful, efficient, and innovative applications.",
  "location": "Lahore, Pakistan",
  "phone": "+92 341-1019063",
  "email": "kazmitech142@gmail.com",
  "github": "https://github.com/farazkazmi700-syed",
  "linkedin": "https://www.linkedin.com/in/muhammad-faraz-kazmi/",
  "skills": {
    "Databases": [
      "MySQL",
      "Firebase",
      "Supabase",
      "Mongo DB"
    ],
    "Languages": [
      "Python"
    ],
    "Libraries": [
      "NumPy",
      "Pandas",
      "Matplotlib",
      "Scikit-learn",
      "Tensorflow",
      "Seaborn",
      "Streamlit",
      "Flask"
    ],
    "LinkedIn Skills": [
      "LangChain",
      "FastAPI"
    ],
    "ML / AI": [
      "Machine Learning",
      "Deep Learning",
      "NLP",
      "Computer Vision",
      "Generative AI",
      "Agentic AI",
      "Feature Engineering"
    ],
    "Methodologies": [
      "Regression",
      "Classification",
      "Recommendation Systems",
      "Systems Automations",
      "Agile"
    ],
    "Tools": [
      "Jupyter Notebook",
      "VS Code",
      "PYcharm",
      "Google Collab",
      "Git",
      "GitHub",
      "Slack"
    ]
  },
  "softSkills": [
    "Leadership",
    "Problem Solving",
    "Teamwork",
    "Communication",
    "Discipline",
    "Time Management",
    "Critical Thinking",
    "Adaptability",
    "Attention to Detail"
  ],
  "experience": [
    {
      "id": 2,
      "title": "Python Tutor",
      "company": "Freelance",
      "period": "Jun 2024 – Dec 2024",
      "description": "Taught basics."
    }
  ],
  "projects": [
    {
      "id": 1,
      "title": "House Price Prediction",
      "description": "Developed ML models for real estate price estimation. Leveraged Multivariant Regression techniques with comprehensive EDA and feature selection.",
      "tags": [
        "Python",
        "Pandas",
        "EDA",
        "Regression"
      ],
      "category": "Machine Learning"
    },
    {
      "id": 2,
      "title": "Multi Turn AI Chatbot with llama3",
      "description": "Built a multi-turn AI chatbot using llama3, capable of understanding context and providing relevant responses. Integrated with a web interface for user interaction.",
      "tags": [
        "Python",
        "llama3",
        "NLP",
        "Chatbot"
      ],
      "category": "Generative AI"
    },
    {
      "id": 3,
      "title": "Plant Disease Detection System",
      "description": "Created a computer vision model to identify plant diseases from leaf images. Utilized CNNs for image classification and deployed the model with a user-friendly interface.",
      "tags": [
        "Python",
        "Computer Vision",
        "CNN",
        "TensorFlow"
      ],
      "category": "Computer Vision"
    }
  ],
  "education": [
    {
      "id": 1,
      "degree": "BS Computer Science (BSCS)",
      "institution": "Virtual University of Pakistan",
      "period": "March 2023 – March 2027",
      "status": "In Progress"
    }
  ],
  "certifications": [
    {
      "id": 2,
      "name": " Python for AI",
      "issuer": "DeepLearning.AI",
      "period": "July 2026"
    },
    {
      "id": 3,
      "name": "Artificial Intelligence on Microsoft Azure",
      "issuer": "Microsoft and offered through Coursera",
      "period": "June, 2026"
    },
    {
      "id": 4,
      "name": "Artificail Intelligence / Machine Learning Course",
      "issuer": "National Vocational Trade Training Center",
      "period": "February 2026 - May 2026"
    }
  ]
};
